In [1]:
import numpy as np

In [ ]:
#assign input values

In [15]:
input_value = np.array([[0,0],[0,1],[1,1],[1,0]])
input_value.shape
input_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [6]:
#assign putput values

In [23]:
output = np.array([[0,1,1,0]])
output = output.reshape(4,1)
output

array([[0],
       [1],
       [1],
       [0]])

In [17]:
#assign weights

In [25]:
weights = np.array([[0.1], [0.2]])
weights.shape

(2, 1)

In [26]:
#add bias

In [27]:
bias = 0.3

In [28]:
#activation function

In [29]:
def sigmoid_func(x):
    return 1/(1+np.exp(-x))

In [30]:
#dervative of functions

In [31]:
def der(x):
    return sigmoid_func(x) * (1-sigmoid_func(x))

In [32]:
#updating weights

In [55]:
for epochs in range(10000):
    input_arr = input_value
    
    weighted_sum = np.dot(input_arr,weights) + bias
    first_output = sigmoid_func(weighted_sum)
    
    error = first_output - output
    total_error = np.square(np.subtract(first_output,output)).mean()
    
    first_der = error
    sercond_der = der(first_output)
    dervative = first_der * sercond_der
    
    t_input = input_value.T
    final_dervative = np.dot(t_input, dervative)
    
    weights= weights - .05 * final_dervative
    
    
    for i in dervative:
        bias = bias - .05 * i
        

print(weights)
print(bias)

[[-0.41210272]
 [11.2213767 ]]
[-5.32019272]


In [58]:
pred = np.array([1,0])
result = np.dot(pred,weights) + bias
res =sigmoid_func(result)
print(res)

[0.00322917]
